- name: Redmineのソースコードをチェックアウト
  become: yes
  become_method: sudo
  git:
    repo={{ redmine_repo }}
    dest={{ redmine_dir }}
    version='v2.3.0'

- name: chown /var/lib/redmine
  become: yes
  become_method: sudo
  command: chown -R www-data.www-data /var/lib/redmine

- name: database.ymlの作成
  become: yes
  become_user: www-data
  become_method: sudo
  template:
    src=database.yml
    dest={{ redmine_dir }}/config/database.yml
    force=no
  register:
    result_database_yml

- name: configuration.ymlの作成
  become: yes
  become_user: www-data
  become_method: sudo
  template:
    src=configuration.yml
    dest={{ redmine_dir }}/config/configuration.yml
    force=no

- name: Gemfile.lockが存在するか確認
  command:
    test -f {{ redmine_dir }}/Gemfile.lock
  register:
    result_test_gemfile
  failed_when: result_test_gemfile.rc not in [0, 1]
  changed_when: false

- name: gemsパッケージのインストール
  become: yes
  become_method: sudo
  command:
    bundle install --without development test
    chdir={{ redmine_dir }}
  when:
    result_test_gemfile.rc == 1

- name: gemsパッケージのアップデート
  become: yes
  become_user: www-data
  become_method: sudo
  command:
    bundle update
    chdir={{ redmine_dir }}
  when:
    result_test_gemfile.rc == 0

- name: secret tokenの作成
  become: yes
  become_user: www-data
  become_method: sudo
  command:
    bundle exec rake generate_secret_token
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production

- name: データベースのマイグレーション
  become: yes
  become_user: www-data
  become_method: sudo
  command:
    bundle exec rake db:migrate
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production

- name: デフォルトデータ(日本語)をロード
  become: yes
  become_user: www-data
  become_method: sudo
  command:
    bundle exec rake redmine:load_default_data
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production
    REDMINE_LANG: ja
  when:
    result_database_yml is changed

- name: farend_basicテーマのダウンロード
  become: yes
  become_user: www-data
  become_method: sudo
  git:
    repo=https://github.com/farend/redmine_theme_farend_basic.git
    dest={{ redmine_dir }}/public/themes/farend_basic

- name: テーマをfarend_basicに切り替え
  become: yes
  become_user: www-data
  become_method: sudo
  command:
    bundle exec rails r 'Setting["ui_theme"]="farend_basic"'
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production
  when:
    result_database_yml is changed

- name: デフォルトの言語を日本語に変更
  become: yes
  become_user: www-data
  become_method: sudo
  command:
    bundle exec rails r 'Setting["default_language"]="ja"'
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production
  when:
    result_database_yml is changed

- name: ユーザー名の表示形式を「姓 名」に変更
  become: yes
  become_user: www-data
  become_method: sudo
  command:
    bundle exec rails r 'Setting["user_format"]=:lastname_firstname'
    chdir={{ redmine_dir }}
  environment:
    RAILS_ENV: production
  when:
    result_database_yml is changed

- name: 添付ファイルとリポジトリのエンコーディングを設定
  become: yes
  become_user: www-data
  become_method: sudo
  command:
    bundle exec rails r 'Setting["repositories_encodings"]="UTF-8,CP932,EUC-JP"'
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production
  when:
    result_database_yml is changed

- name: 添付ファイルのサムネイルを表示
  become: yes
  become_user: www-data
  become_method: sudo
  command:
    bundle exec rails r 'Setting["thumbnails_enabled"]="1"'
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production
  when:
    result_database_yml is changed
